/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Shai } from "./Shai";
import { ShaiCountArgs } from "./ShaiCountArgs";
import { ShaiFindManyArgs } from "./ShaiFindManyArgs";
import { ShaiFindUniqueArgs } from "./ShaiFindUniqueArgs";
import { DeleteShaiArgs } from "./DeleteShaiArgs";
import { ShaiService } from "../shai.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Shai)
export class ShaiResolverBase {
  constructor(
    protected readonly service: ShaiService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Shai",
    action: "read",
    possession: "any",
  })
  async _shaisMeta(
    @graphql.Args() args: ShaiCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Shai])
  @nestAccessControl.UseRoles({
    resource: "Shai",
    action: "read",
    possession: "any",
  })
  async shais(@graphql.Args() args: ShaiFindManyArgs): Promise<Shai[]> {
    return this.service.shais(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Shai, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Shai",
    action: "read",
    possession: "own",
  })
  async shai(@graphql.Args() args: ShaiFindUniqueArgs): Promise<Shai | null> {
    const result = await this.service.shai(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shai)
  @nestAccessControl.UseRoles({
    resource: "Shai",
    action: "delete",
    possession: "any",
  })
  async deleteShai(@graphql.Args() args: DeleteShaiArgs): Promise<Shai | null> {
    try {
      return await this.service.deleteShai(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
